// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 007_get_user_from_uid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getUserFromUserId = `-- name: GetUserFromUserId :one
SELECT
    name
FROM
    users
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetUserFromUserId(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserFromUserId, id)
	var name string
	err := row.Scan(&name)
	return name, err
}
