// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 010_get_feed_from_url.sql

package database

import (
	"context"
	"database/sql"
)

const getFeedFromURL = `-- name: GetFeedFromURL :one
SELECT
    id, created_at, updated_at, name, url, user_id
FROM
    feeds
WHERE
    url = $1
LIMIT 1
`

func (q *Queries) GetFeedFromURL(ctx context.Context, url sql.NullString) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedFromURL, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
