// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 011_get_feed_from_fid.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedFromFeedId = `-- name: GetFeedFromFeedId :one
SELECT
    id, created_at, updated_at, name, url, user_id
FROM
    feeds
WHERE
    id = $1
LIMIT 1
`

func (q *Queries) GetFeedFromFeedId(ctx context.Context, id uuid.UUID) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedFromFeedId, id)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
	)
	return i, err
}
